spring.application.name=simondesdevises

spring.datasource.url=jdbc:h2:mem:sondage;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

spring.sql.init.mode=always

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.h2.console.enabled=true

spring.security.user.name=unused
spring.security.user.password=unused
