spring.application.name=tp509

# SQL
spring.datasource.url=jdbc:h2:mem:archilog;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.username=sa
spring.datasource.password=

# import.SQL
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Servlet
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Security
spring.security.user.name=root
spring.security.user.password=root
