spring.application.name=tp506c

# SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/archilog
spring.datasource.username=postgres
spring.datasource.password=postgres

# import.SQL
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
